export default {
  GET_GROUP_BY_ID: "GET_GROUP_BY_ID",
  CREATE_GROUP: "CREATE_GROUP",
  ADD_USER_TO_GROUP: "ADD_USER_TO_GROUP",
  CREATE_MENU_ITEM: "CREATE_MENU_ITEM",
  UPDATE_MENU_ITEM: "UPDATE_MENU_ITEM",
  REMOVE_USER_FROM_GROUP: "REMOVE_USER_FROM_GROUP",
  REMOVE_MENU_FROM_GROUP: "REMOVE_MENU_FROM_GROUP",
  CREATE_EVENT: "CREATE_EVENT",
};
